version: '3.9'

services:
  ongdb:
    image: neo4j:latest
    container_name: ongdb
    environment:
      - NEO4J_AUTH=neo4j/fulanoPass
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ongdb_data:/data
    restart: always
  app:
    build: .
    container_name: java-app
    depends_on:
      - ongdb
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  ongdb_data:
